apiVersion: v1
kind: Pod
metadata:
  labels:
    app: alpine
  name: alpine
spec:
  automountServiceAccountToken: false
  containers:
    - name: alpine
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      args:
        - sleep
        - infinite
